{application,ecto_enum,
             [{applications,[kernel,stdlib,elixir,logger,ecto]},
              {description,"Ecto extension to support enums in models"},
              {modules,['Elixir.EctoEnum','Elixir.EctoEnum.Postgres',
                        'Elixir.EctoEnum.Postgres.Use',
                        'Elixir.EctoEnum.Typespec',
                        'Elixir.EctoEnum.Typespec.TestModule',
                        'Elixir.EctoEnum.Typespec.TestModule.PGStatusEnum',
                        'Elixir.EctoEnum.Typespec.TestModule.StatusEnum',
                        'Elixir.EctoEnum.Use']},
              {registered,[]},
              {vsn,"1.3.2"}]}.
